// Overall "how well am I using Claude Code + improvements" report, generated by
// calling the local claude CLI (subscription). Cached until regenerated.
import { getCcReview, getCcStats } from "@/lib/db";
import { renderMarkdown } from "@/lib/md";
import { ReviewButton } from "../ReviewButton";
import { Breadcrumb } from "../../Breadcrumb";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const card: React.CSSProperties = {
  background: "#11151d",
  border: "1px solid #1f2530",
  borderRadius: 12,
  padding: "20px 22px",
};

export default function CcReviewPage() {
  const review = getCcReview("overall", null);
  const stats = getCcStats();

  return (
    <main style={{ maxWidth: 820, margin: "0 auto", padding: "32px 20px 64px" }}>
      <Breadcrumb
        items={[
          { label: "대시보드", href: "/dashboard" },
          { label: "Claude Code 분석", href: "/dashboard/cc" },
          { label: "활용 리뷰" },
        ]}
      />
      <h1 style={{ fontSize: 22, margin: 0 }}>Claude Code 활용 리뷰</h1>
      <p style={{ color: "#9ca3af", fontSize: 13, marginTop: 6 }}>
        로컬 <code>claude</code> CLI(구독)로 내 요청을 분석해 개선점을 도출합니다 — API key 불필요.
      </p>

      <div style={{ margin: "14px 0", display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
        <ReviewButton scope="overall" hasReport={!!review} />
        {review && (
          <span style={{ color: "#6b7280", fontSize: 12 }}>
            생성: {new Date(review.created_at).toLocaleString("ko-KR")}
          </span>
        )}
      </div>

      {stats.sessions === 0 ? (
        <div style={{ ...card, color: "#9ca3af", fontSize: 13 }}>
          스캔된 Claude Code 세션이 없습니다. 먼저 <a href="/dashboard/cc" style={{ color: "#7dd3fc" }}>활용 분석</a>을 열어 스캔하세요.
        </div>
      ) : !review ? (
        <div style={{ ...card, color: "#9ca3af", fontSize: 13, lineHeight: 1.7 }}>
          아직 리뷰가 없습니다. 위 <b>"Claude로 개선점 분석"</b> 버튼을 누르면 로컬 claude가
          내 요청 패턴을 분석해 개선점(더 나은 요청 예시 포함)을 리포트로 만들어 줍니다.
        </div>
      ) : (
        <article
          style={card}
          dangerouslySetInnerHTML={{ __html: renderMarkdown(review.content) }}
        />
      )}
    </main>
  );
}
