// SQLite storage backed by Node's builtin `node:sqlite` (synchronous, no native
// install). One DB file lives at server/data.sqlite. The connection is cached on
// globalThis so Next.js dev HMR doesn't reopen it on every module re-eval.
import { DatabaseSync } from "node:sqlite";
import path from "node:path";

const DB_PATH = path.join(process.cwd(), "data.sqlite");

type GlobalWithDb = typeof globalThis & { __ctDb?: DatabaseSync };

function init(): DatabaseSync {
  const db = new DatabaseSync(DB_PATH);
  db.exec("PRAGMA journal_mode = WAL;");
  db.exec(`
    CREATE TABLE IF NOT EXISTS snapshots (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_email TEXT NOT NULL,
      provider TEXT,
      plan TEXT,
      org_uuid TEXT,
      install_id TEXT,
      five_hour_utilization REAL,
      five_hour_resets_at TEXT,
      seven_day_utilization REAL,
      seven_day_resets_at TEXT,
      extra_usage_used REAL,
      extra_usage_limit REAL,
      collected_at TEXT,
      raw TEXT,
      created_at TEXT NOT NULL
    );
  `);

  // Migration: older DBs predate the provider column. Add it and backfill from
  // raw so existing rows (Claude/ChatGPT/Gemini mixed under one email) split.
  const cols = db
    .prepare("SELECT name FROM pragma_table_info('snapshots')")
    .all() as unknown as { name: string }[];
  if (!cols.some((c) => c.name === "provider")) {
    db.exec("ALTER TABLE snapshots ADD COLUMN provider TEXT");
  }
  const needBackfill = db
    .prepare("SELECT id, raw FROM snapshots WHERE provider IS NULL")
    .all() as unknown as { id: number; raw: string }[];
  if (needBackfill.length) {
    const upd = db.prepare("UPDATE snapshots SET provider = ? WHERE id = ?");
    for (const r of needBackfill) {
      let p = "claude";
      try {
        p = JSON.parse(r.raw).provider || "claude";
      } catch {
        /* keep default */
      }
      upd.run(p, r.id);
    }
  }

  db.exec(
    "CREATE INDEX IF NOT EXISTS idx_snapshots_email_provider_collected ON snapshots(user_email, provider, collected_at);"
  );

  // Claude Code (CLI) transcripts scanned from ~/.claude/projects.
  // Migration: drop pre-user-metrics cc tables so they rebuild with the new
  // schema (a full rescan repopulates everything from the local transcripts).
  const ccCols = db
    .prepare("SELECT name FROM pragma_table_info('cc_sessions')")
    .all() as unknown as { name: string }[];
  if (ccCols.length && !ccCols.some((c) => c.name === "user_turns")) {
    db.exec("DROP TABLE IF EXISTS cc_messages");
    db.exec("DROP TABLE IF EXISTS cc_sessions");
  }
  db.exec(`
    CREATE TABLE IF NOT EXISTS cc_sessions (
      session_id TEXT PRIMARY KEY,
      project TEXT,
      cwd TEXT,
      title TEXT,
      git_branch TEXT,
      cc_version TEXT,
      started_at TEXT,
      ended_at TEXT,
      message_count INTEGER DEFAULT 0,
      input_tokens INTEGER DEFAULT 0,
      output_tokens INTEGER DEFAULT 0,
      cache_tokens INTEGER DEFAULT 0,
      user_turns INTEGER DEFAULT 0,
      user_chars INTEGER DEFAULT 0,
      first_user_prompt TEXT,
      source_path TEXT,
      mtime_ms INTEGER,
      synced_at TEXT
    );
  `);
  db.exec(`
    CREATE TABLE IF NOT EXISTS cc_messages (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      idx INTEGER,
      role TEXT,
      kind TEXT,
      text TEXT,
      tool_name TEXT,
      created_at TEXT
    );
  `);
  db.exec(
    "CREATE INDEX IF NOT EXISTS idx_cc_sessions_started ON cc_sessions(started_at);"
  );
  db.exec(
    "CREATE INDEX IF NOT EXISTS idx_cc_messages_session ON cc_messages(session_id, idx);"
  );

  // LLM review reports generated by calling the `claude` CLI (scope: overall|session).
  db.exec(`
    CREATE TABLE IF NOT EXISTS cc_reviews (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      scope TEXT NOT NULL,
      session_id TEXT,
      content TEXT,
      created_at TEXT
    );
  `);
  return db;
}

export function getDb(): DatabaseSync {
  const g = globalThis as GlobalWithDb;
  if (!g.__ctDb) g.__ctDb = init();
  return g.__ctDb;
}

// Shape the extension expects in recent_snapshots[] (see bg/storage.js
// mergeServerSnapshots: it reads exactly these keys).
export interface RecentSnapshot {
  collected_at: string;
  five_hour_utilization: number | null;
  five_hour_resets_at: string | null;
  seven_day_utilization: number | null;
  seven_day_resets_at: string | null;
  extra_usage_used: number | null;
  extra_usage_limit: number | null;
}

export interface InsertSnapshotInput {
  user_email: string;
  provider: string;
  plan: string | null;
  org_uuid: string | null;
  install_id: string | null;
  five_hour_utilization: number | null;
  five_hour_resets_at: string | null;
  seven_day_utilization: number | null;
  seven_day_resets_at: string | null;
  extra_usage_used: number | null;
  extra_usage_limit: number | null;
  collected_at: string;
  raw: string;
}

export function insertSnapshot(s: InsertSnapshotInput): void {
  const db = getDb();
  db.prepare(
    `INSERT INTO snapshots (
       user_email, provider, plan, org_uuid, install_id,
       five_hour_utilization, five_hour_resets_at,
       seven_day_utilization, seven_day_resets_at,
       extra_usage_used, extra_usage_limit,
       collected_at, raw, created_at
     ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
  ).run(
    s.user_email,
    s.provider,
    s.plan,
    s.org_uuid,
    s.install_id,
    s.five_hour_utilization,
    s.five_hour_resets_at,
    s.seven_day_utilization,
    s.seven_day_resets_at,
    s.extra_usage_used,
    s.extra_usage_limit,
    s.collected_at,
    s.raw,
    new Date().toISOString()
  );
}

interface QueryOpts {
  provider?: string | null;
  orgUuid?: string | null;
}

// Most recent N snapshots for a user, returned oldest→newest (chart-friendly).
// Optional provider/org filters keep different services (Claude/Gemini/ChatGPT)
// from bleeding into one timeline.
export function getRecentSnapshots(
  email: string,
  limit = 200,
  opts: QueryOpts = {}
): RecentSnapshot[] {
  const db = getDb();
  const clauses = ["user_email = ?"];
  const args: (string | number)[] = [email];
  if (opts.provider) {
    clauses.push("provider = ?");
    args.push(opts.provider);
  }
  if (opts.orgUuid) {
    clauses.push("org_uuid = ?");
    args.push(opts.orgUuid);
  }
  args.push(limit);
  const rows = db
    .prepare(
      `SELECT collected_at, five_hour_utilization, five_hour_resets_at,
              seven_day_utilization, seven_day_resets_at,
              extra_usage_used, extra_usage_limit
       FROM snapshots
       WHERE ${clauses.join(" AND ")}
       ORDER BY collected_at DESC
       LIMIT ?`
    )
    .all(...args) as unknown as RecentSnapshot[];
  return rows.reverse();
}

export function getLatestSnapshot(
  email: string,
  provider?: string | null
): (RecentSnapshot & { plan: string | null }) | null {
  const db = getDb();
  const clauses = ["user_email = ?"];
  const args: string[] = [email];
  if (provider) {
    clauses.push("provider = ?");
    args.push(provider);
  }
  const row = db
    .prepare(
      `SELECT plan, collected_at, five_hour_utilization, five_hour_resets_at,
              seven_day_utilization, seven_day_resets_at,
              extra_usage_used, extra_usage_limit
       FROM snapshots
       WHERE ${clauses.join(" AND ")}
       ORDER BY collected_at DESC
       LIMIT 1`
    )
    .get(...args) as (RecentSnapshot & { plan: string | null }) | undefined;
  return row ?? null;
}

export interface UserSummary {
  user_email: string;
  count: number;
  latest: string;
}

// Distinct users with snapshot counts, most-recently-active first.
export function getUsers(): UserSummary[] {
  const db = getDb();
  return db
    .prepare(
      `SELECT user_email, COUNT(*) AS count, MAX(collected_at) AS latest
       FROM snapshots
       GROUP BY user_email
       ORDER BY latest DESC`
    )
    .all() as unknown as UserSummary[];
}

export interface ProviderSummary {
  provider: string;
  count: number;
  latest: string;
}

// Distinct providers seen for one email (Claude/Gemini/ChatGPT), so the
// dashboard can offer a per-provider view instead of mixing them.
export function getProvidersForEmail(email: string): ProviderSummary[] {
  const db = getDb();
  return db
    .prepare(
      `SELECT COALESCE(provider, 'claude') AS provider,
              COUNT(*) AS count, MAX(collected_at) AS latest
       FROM snapshots
       WHERE user_email = ?
       GROUP BY COALESCE(provider, 'claude')
       ORDER BY count DESC`
    )
    .all(email) as unknown as ProviderSummary[];
}

// ── Long-range aggregates ───────────────────────────────────────────────────

export interface DailyUsage {
  date: string; // YYYY-MM-DD (UTC, from collected_at prefix)
  five_hour_max: number | null;
  seven_day_max: number | null;
  count: number;
}

// Daily down-sample for long-range trend charts: per-UTC-day peak utilization.
// substr(collected_at,1,10) avoids SQLite date() timezone surprises (collected_at
// is ISO). Peak (MAX) per day is the meaningful signal for usage windows.
export function getDailyUsage(
  email: string,
  days = 180,
  provider?: string | null
): DailyUsage[] {
  const db = getDb();
  const cutoff = new Date(Date.now() - days * 86400000).toISOString();
  const clauses = ["user_email = ?", "collected_at >= ?"];
  const args: (string | number)[] = [email, cutoff];
  if (provider) {
    clauses.push("provider = ?");
    args.push(provider);
  }
  return db
    .prepare(
      `SELECT substr(collected_at, 1, 10) AS date,
              MAX(five_hour_utilization) AS five_hour_max,
              MAX(seven_day_utilization) AS seven_day_max,
              COUNT(*) AS count
       FROM snapshots
       WHERE ${clauses.join(" AND ")}
       GROUP BY substr(collected_at, 1, 10)
       ORDER BY date ASC`
    )
    .all(...args) as unknown as DailyUsage[];
}

export interface WindowPeak {
  resets_at: string;
  peak: number | null;
  count: number;
}

// Per reset-window peak utilization. Same resets_at = same window, so MAX(util)
// over that group = how high that 5h/7d cycle reached. Drives "limit-reached
// frequency" and long-range peak trend for plan recommendation.
export function getWindowPeaks(
  email: string,
  windowKey: "five_hour" | "seven_day",
  days = 180,
  provider?: string | null
): WindowPeak[] {
  const db = getDb();
  const utilCol =
    windowKey === "five_hour"
      ? "five_hour_utilization"
      : "seven_day_utilization";
  const resetCol =
    windowKey === "five_hour" ? "five_hour_resets_at" : "seven_day_resets_at";
  const cutoff = new Date(Date.now() - days * 86400000).toISOString();
  const clauses = [
    "user_email = ?",
    "collected_at >= ?",
    `${resetCol} IS NOT NULL`,
  ];
  const args: (string | number)[] = [email, cutoff];
  if (provider) {
    clauses.push("provider = ?");
    args.push(provider);
  }
  return db
    .prepare(
      `SELECT ${resetCol} AS resets_at, MAX(${utilCol}) AS peak, COUNT(*) AS count
       FROM snapshots
       WHERE ${clauses.join(" AND ")}
       GROUP BY ${resetCol}
       ORDER BY resets_at ASC`
    )
    .all(...args) as unknown as WindowPeak[];
}

// ── Claude Code (CLI) transcripts ───────────────────────────────────────────

export interface CcMessageInput {
  idx: number;
  role: string | null;
  kind: string | null;
  text: string | null;
  tool_name: string | null;
  created_at: string | null;
}
export interface CcSessionInput {
  session_id: string;
  project: string | null;
  cwd: string | null;
  title: string | null;
  git_branch: string | null;
  cc_version: string | null;
  started_at: string | null;
  ended_at: string | null;
  input_tokens: number;
  output_tokens: number;
  cache_tokens: number;
  user_turns: number;
  user_chars: number;
  first_user_prompt: string | null;
  source_path: string;
  mtime_ms: number;
  messages: CcMessageInput[];
}

// session_id → mtime_ms, for incremental scan (skip unchanged files).
export function getCcSessionMtimes(): Map<string, number> {
  const db = getDb();
  const rows = db
    .prepare("SELECT session_id, mtime_ms FROM cc_sessions")
    .all() as unknown as { session_id: string; mtime_ms: number }[];
  return new Map(rows.map((r) => [r.session_id, r.mtime_ms]));
}

export function upsertCcSession(s: CcSessionInput): void {
  const db = getDb();
  db.prepare(
    `INSERT INTO cc_sessions
       (session_id, project, cwd, title, git_branch, cc_version, started_at, ended_at,
        message_count, input_tokens, output_tokens, cache_tokens,
        user_turns, user_chars, first_user_prompt, source_path, mtime_ms, synced_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(session_id) DO UPDATE SET
       project=excluded.project, cwd=excluded.cwd, title=excluded.title,
       git_branch=excluded.git_branch, cc_version=excluded.cc_version,
       started_at=excluded.started_at, ended_at=excluded.ended_at,
       message_count=excluded.message_count, input_tokens=excluded.input_tokens,
       output_tokens=excluded.output_tokens, cache_tokens=excluded.cache_tokens,
       user_turns=excluded.user_turns, user_chars=excluded.user_chars,
       first_user_prompt=excluded.first_user_prompt,
       source_path=excluded.source_path, mtime_ms=excluded.mtime_ms, synced_at=excluded.synced_at`
  ).run(
    s.session_id,
    s.project,
    s.cwd,
    s.title,
    s.git_branch,
    s.cc_version,
    s.started_at,
    s.ended_at,
    s.messages.length,
    s.input_tokens,
    s.output_tokens,
    s.cache_tokens,
    s.user_turns,
    s.user_chars,
    s.first_user_prompt,
    s.source_path,
    s.mtime_ms,
    new Date().toISOString()
  );
  db.prepare("DELETE FROM cc_messages WHERE session_id = ?").run(s.session_id);
  const ins = db.prepare(
    "INSERT INTO cc_messages (session_id, idx, role, kind, text, tool_name, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)"
  );
  for (const m of s.messages) {
    ins.run(s.session_id, m.idx, m.role, m.kind, m.text, m.tool_name, m.created_at);
  }
}

export interface CcSessionRow {
  session_id: string;
  project: string | null;
  title: string | null;
  git_branch: string | null;
  cc_version: string | null;
  started_at: string | null;
  ended_at: string | null;
  message_count: number;
  input_tokens: number;
  output_tokens: number;
  cache_tokens: number;
  user_turns: number;
  user_chars: number;
  first_user_prompt: string | null;
}

const CC_SESSION_COLS = `session_id, project, title, git_branch, cc_version, started_at, ended_at,
              message_count, input_tokens, output_tokens, cache_tokens,
              user_turns, user_chars, first_user_prompt`;

export function getCcSessions(
  opts: { project?: string | null; search?: string | null; limit?: number } = {}
): CcSessionRow[] {
  const db = getDb();
  const clauses: string[] = [];
  const args: (string | number)[] = [];
  if (opts.project) {
    clauses.push("project = ?");
    args.push(opts.project);
  }
  if (opts.search) {
    clauses.push("(title LIKE ? OR project LIKE ? OR first_user_prompt LIKE ?)");
    args.push(`%${opts.search}%`, `%${opts.search}%`, `%${opts.search}%`);
  }
  args.push(opts.limit ?? 500);
  const where = clauses.length ? `WHERE ${clauses.join(" AND ")}` : "";
  return db
    .prepare(
      `SELECT ${CC_SESSION_COLS}
       FROM cc_sessions ${where}
       ORDER BY ended_at DESC
       LIMIT ?`
    )
    .all(...args) as unknown as CcSessionRow[];
}

export function getCcSession(sessionId: string): CcSessionRow | null {
  const db = getDb();
  const row = db
    .prepare(`SELECT ${CC_SESSION_COLS} FROM cc_sessions WHERE session_id = ?`)
    .get(sessionId) as CcSessionRow | undefined;
  return row ?? null;
}

// ── Usage-pattern aggregates ────────────────────────────────────────────────

export interface ToolUsage {
  tool_name: string;
  uses: number;
}
// What I ask Claude Code to DO — tool_use frequency by tool name.
export function getCcToolUsage(limit = 15): ToolUsage[] {
  const db = getDb();
  return db
    .prepare(
      `SELECT COALESCE(tool_name, '(unknown)') AS tool_name, COUNT(*) AS uses
       FROM cc_messages
       WHERE kind = 'tool_use'
       GROUP BY tool_name
       ORDER BY uses DESC
       LIMIT ?`
    )
    .all(limit) as unknown as ToolUsage[];
}

export interface HourActivity {
  hour: number; // 0–23 (local? stored UTC ISO; use substr)
  sessions: number;
}
// When I use Claude Code — session starts by UTC hour-of-day.
export function getCcActivityByHour(): HourActivity[] {
  const db = getDb();
  const rows = db
    .prepare(
      `SELECT CAST(substr(started_at, 12, 2) AS INTEGER) AS hour, COUNT(*) AS sessions
       FROM cc_sessions
       WHERE started_at IS NOT NULL
       GROUP BY hour
       ORDER BY hour ASC`
    )
    .all() as unknown as HourActivity[];
  return rows;
}

// My requests only (role=user, kind=text) for a session — the conversation view
// makes these the primary content.
export function getCcUserMessages(sessionId: string): CcMessageRow[] {
  const db = getDb();
  return db
    .prepare(
      `SELECT idx, role, kind, text, tool_name, created_at
       FROM cc_messages
       WHERE session_id = ? AND role = 'user' AND kind = 'text'
       ORDER BY idx ASC`
    )
    .all(sessionId) as unknown as CcMessageRow[];
}

export interface CcMessageRow {
  idx: number;
  role: string | null;
  kind: string | null;
  text: string | null;
  tool_name: string | null;
  created_at: string | null;
}
export function getCcMessages(sessionId: string): CcMessageRow[] {
  const db = getDb();
  return db
    .prepare(
      `SELECT idx, role, kind, text, tool_name, created_at
       FROM cc_messages WHERE session_id = ? ORDER BY idx ASC`
    )
    .all(sessionId) as unknown as CcMessageRow[];
}

export interface CcDayTokens {
  date: string;
  input_tokens: number;
  output_tokens: number;
  cache_tokens: number;
  sessions: number;
}
// Per-day token totals (by session started_at) for the usage trend chart.
export function getCcDailyTokens(days = 180): CcDayTokens[] {
  const db = getDb();
  const cutoff = new Date(Date.now() - days * 86400000).toISOString();
  return db
    .prepare(
      `SELECT substr(started_at, 1, 10) AS date,
              SUM(input_tokens) AS input_tokens,
              SUM(output_tokens) AS output_tokens,
              SUM(cache_tokens) AS cache_tokens,
              COUNT(*) AS sessions
       FROM cc_sessions
       WHERE started_at >= ?
       GROUP BY substr(started_at, 1, 10)
       ORDER BY date ASC`
    )
    .all(cutoff) as unknown as CcDayTokens[];
}

export interface CcProjectTokens {
  project: string | null;
  input_tokens: number;
  output_tokens: number;
  cache_tokens: number;
  sessions: number;
  messages: number;
}
export function getCcProjectTokens(days = 180): CcProjectTokens[] {
  const db = getDb();
  const cutoff = new Date(Date.now() - days * 86400000).toISOString();
  return db
    .prepare(
      `SELECT project,
              SUM(input_tokens) AS input_tokens,
              SUM(output_tokens) AS output_tokens,
              SUM(cache_tokens) AS cache_tokens,
              COUNT(*) AS sessions,
              SUM(message_count) AS messages
       FROM cc_sessions
       WHERE started_at >= ?
       GROUP BY project
       ORDER BY (SUM(input_tokens)+SUM(output_tokens)) DESC`
    )
    .all(cutoff) as unknown as CcProjectTokens[];
}

export interface CcStats {
  sessions: number;
  messages: number;
  input_tokens: number;
  output_tokens: number;
  cache_tokens: number;
}
export function getCcStats(): CcStats {
  const db = getDb();
  const r = db
    .prepare(
      `SELECT COUNT(*) AS sessions,
              COALESCE(SUM(message_count),0) AS messages,
              COALESCE(SUM(input_tokens),0) AS input_tokens,
              COALESCE(SUM(output_tokens),0) AS output_tokens,
              COALESCE(SUM(cache_tokens),0) AS cache_tokens
       FROM cc_sessions`
    )
    .get() as unknown as CcStats;
  return r;
}

// ── CC review reports (claude CLI output) ───────────────────────────────────

export interface CcReview {
  content: string;
  created_at: string;
}

export function setCcReview(
  scope: string,
  sessionId: string | null,
  content: string
): void {
  const db = getDb();
  db.prepare(
    "DELETE FROM cc_reviews WHERE scope = ? AND IFNULL(session_id,'') = IFNULL(?,'')"
  ).run(scope, sessionId);
  db.prepare(
    "INSERT INTO cc_reviews (scope, session_id, content, created_at) VALUES (?, ?, ?, ?)"
  ).run(scope, sessionId, content, new Date().toISOString());
}

export function getCcReview(
  scope: string,
  sessionId: string | null
): CcReview | null {
  const db = getDb();
  const row = db
    .prepare(
      `SELECT content, created_at FROM cc_reviews
       WHERE scope = ? AND IFNULL(session_id,'') = IFNULL(?,'')
       ORDER BY created_at DESC LIMIT 1`
    )
    .get(scope, sessionId) as CcReview | undefined;
  return row ?? null;
}
